version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
  slack: circleci/slack@4.2.1
workflows:
  build:
    jobs:
    steps:
      - checkout master
      - cypress/install
      - cypress/run:
          name: UI Test
          requires:
            - cypress/install
          command: npx cypress run
          record: true
          post-steps:
            - slack/notify:
                channel: $SLACK_DEFAULT_CHANNEL
                event: fail
                template: basic_fail_1
            - slack/notify:
                channel: $SLACK_DEFAULT_CHANNEL
                event: pass
                template: success_tagged_deploy_1
